title: Reese
email: reeselevine1@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Just another personal website
author: reese
baseurl: /introspect # the subpath of your site, e.g. /blog
url: https://reeselevine.github.io
twitter_username: reeselevine
github_username:  reeselevine

google_analytics: UA-65317036-1

# Build settings
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
